export const Chats = [
  {
    id: "cnv1",
    name: "Jorge de Guzman",
    lastMessage: "Helloooo",
    img: "/images/lalosalamanca.jpg",
    status: "online",
    time: "13:45",
    unread: 0,
  },
  {
    id: "cnv2",
    name: "Lalo Salamanca",
    lastMessage: "okay sure",
    img: "/images/ll.jpg",
    status: "offline",
    time: "00:26",
    unread: 3,
  },
  {
    id: "cnv3",
    name: "Nacho De Varga",
    lastMessage: "Helloooo",
    img: "/images/nacho.jpg",
    status: "online",
    time: "02:40",
    unread: 0,
  },
  {
    id: "cnv4",
    name: "Gus",
    lastMessage: "Helloooo",
    img: "/images/gus.png",
    status: "online",
    time: "02:40",
    unread: 0,
  },
];

export const groupChats = [
  {
    id: "grp1",
    name: "General",
    unread: 0,
  },
  {
    id: "grp2",
    name: "Fun",
    unread: 1,
  },
  {
    id: "grp3",
    name: "Discovery",
    lastMessage: "Helloooo",
    unread: 4,
  },
  {
    id: "grp4",
    name: "Meetings",
    unread: 2,
  },
];

export const Messages = [
  [
    {
      sender: "Jorge de Guzman",
      content: "heloooo",
      isRight: false,
      time: "13:38",
      img: "/images/lalosalamanca.jpg",
      received: true,
    },
    {
      sender: "You",
      content: "how are you ?",
      isRight: true,
      time: "13:38",
      img: "/images/oussama.jpg",
      received: false,
    },
    {
      sender: "Jorge de Guzman",
      content: "Im good",
      isRight: false,
      time: "13:39",
      img: "/images/lalosalamanca.jpg",
      received: true,
    },
    {
      sender: "Jorge de Guzman",
      content: "Do you need any help?",
      isRight: false,
      time: "13:39",
      img: "/images/lalosalamanca.jpg",
      received: true,
    },
    {
      sender: "You",
      content: "No thank you",
      isRight: true,
      time: "13:42",
      img: "/images/oussama.jpg",
      received: false,
    },
    {
      sender: "Jorge de Guzman",
      content: "Did you advance on your last project ?",
      isRight: false,
      time: "13:43",
      img: "/images/lalosalamanca.jpg",
      received: true,
    },
    {
      sender: "Jorge de Guzman",
      content: "The one you told me yesterday",
      isRight: false,
      time: "13:44",
      img: "/images/lalosalamanca.jpg",
      received: true,
    },
    {
      sender: "You",
      content: "Ah! No, not really",
      isRight: true,
      time: "13:45",
      img: "/images/oussama.jpg",
      received: false,
    },
    {
      sender: "You",
      content: "I was busy this week",
      isRight: true,
      time: "13:45",
      img: "/images/oussama.jpg",
      received: false,
    },
  ],
  [
    {
      sender: "Lalo Salamnca",
      content: "hi",
      isRight: false,
      time: "00:15",
      img: "/images/ll.jpg",
      received: true,
    },
    {
      sender: "You",
      content: "Helo",
      isRight: true,
      time: "00:19",
      img: "/images/oussama.jpg",
      received: false,
    },
    {
      sender: "Lalo Salamnca",
      content: "Did you see Gus ?",
      isRight: false,
      time: "00:21",
      img: "/images/ll.jpg",
      received: true,
    },
    {
      sender: "Lalo Salamnca",
      content: "The chicken man",
      isRight: false,
      time: "00:21",
      img: "/images/ll.jpg",
      received: true,
    },
    {
      sender: "You",
      content: "Yes",
      isRight: true,
      time: "00:24",
      img: "/images/oussama.jpg",
      received: false,
    },
    {
      sender: "Lalo Salamnca",
      content: "Did he finish the work on his underground lab ?",
      isRight: false,
      time: "00:24",
      img: "/images/ll.jpg",
      received: true,
    },
    {
      sender: "Lalo Salamnca",
      content: "I saw some progress last week",
      isRight: false,
      time: "00:24",
      img: "/images/ll.jpg",
      received: true,
    },
    {
      sender: "You",
      content: "Yes",
      isRight: true,
      time: "00:25",
      img: "/images/oussama.jpg",
      received: false,
    },
    {
      sender: "You",
      content: "It's almost over.",
      isRight: true,
      time: "00:26",
      img: "/images/oussama.jpg",
      received: false,
    },
  ],
  [],
  [],
];
