export const Chats = [
  {
    name: "Lalo Salamanca",
    lastMessage: "Helloooo",
    img: null,
    status: "online",
    time: "02:40",
    unread: 0,
    active: true,
  },
  {
    name: "Jorge De Guzmàn",
    lastMessage: "okay sure",
    img: null,
    status: "away",
    time: "12:40",
    unread: 3,
    active: false,
  },
  {
    name: "Lalo Salamanca",
    lastMessage: "Helloooo",
    img: null,
    status: "online",
    time: "02:40",
    unread: 0,
    active: false,
  },
  {
    name: "Lalo Salamanca",
    lastMessage: "Helloooo",
    img: null,
    status: "online",
    time: "02:40",
    unread: 0,
    active: false,
  },
];

export const Messages = [
  {
    sender: "Lalo Salamnca",
    content: "hi",
    isRight: false,
    time: "00:42",
    img: null,
    received: true,
  },
  {
    sender: "Lalo Salamnca",
    content: "hi",
    isRight: true,
    time: "00:42",
    img: null,
    received: false,
  },
  {
    sender: "Lalo Salamnca",
    content: "how's going on your project?",
    isRight: false,
    time: "00:42",
    img: null,
    received: true,
  },
  {
    sender: "Lalo Salamnca",
    content: "Do you need any help?",
    isRight: false,
    time: "00:42",
    img: null,
    received: true,
  },
  {
    sender: "Lalo Salamnca",
    content: "Hello",
    isRight: true,
    time: "00:42",
    img: null,
    received: false,
  },
  {
    sender: "Lalo Salamnca",
    content: "how's going on your project?",
    isRight: false,
    time: "00:42",
    img: null,
    received: true,
  },
  {
    sender: "Lalo Salamnca",
    content: "Do you need any help?",
    isRight: false,
    time: "00:42",
    img: null,
    received: true,
  },
  {
    sender: "Lalo Salamnca",
    content: "Hey there!",
    isRight: true,
    time: "00:42",
    img: null,
    received: false,
  },
  {
    sender: "Lalo Salamnca",
    content: "Hey thereeeeeee!",
    isRight: true,
    time: "00:43",
    img: null,
    received: false,
  },
];
