export const Chats = [
  {
    id: "cnv1",
    name: "Jorge de Guzman",
    lastMessage: "Helloooo",
    img: null,
    status: "online",
    time: "02:40",
    unread: 0,
  },
  {
    id: "cnv2",
    name: "Lalo Salamanca",
    lastMessage: "okay sure",
    img: null,
    status: "away",
    time: "12:40",
    unread: 3,
  },
  {
    id: "cnv3",
    name: "Nacho De Varga",
    lastMessage: "Helloooo",
    img: null,
    status: "online",
    time: "02:40",
    unread: 0,
  },
  {
    id: "cnv4",
    name: "Gus",
    lastMessage: "Helloooo",
    img: null,
    status: "online",
    time: "02:40",
    unread: 0,
  },
];

export const groupChats = [
  {
    id: "grp1",
    name: "General",
    unread: 0,
  },
  {
    id: "grp2",
    name: "Fun",
    unread: 1,
  },
  {
    id: "grp3",
    name: "Discovery",
    lastMessage: "Helloooo",
    unread: 4,
  },
  {
    id: "grp4",
    name: "Meetings",
    unread: 2,
  },
];

export const Messages = [
  [
    {
      sender: "Jorge de Guzman",
      content: "heloooo",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Ana",
      content: "how are you ?",
      isRight: true,
      time: "00:42",
      img: null,
      received: false,
    },
    {
      sender: "Jorge de Guzman",
      content: "Trgud b alf ?",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Jorge de Guzman",
      content: "Do you need any help?",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Ana",
      content: "laaaa",
      isRight: true,
      time: "00:42",
      img: null,
      received: false,
    },
    {
      sender: "Jorge de Guzman",
      content: "Jacketa nadya",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Jorge de Guzman",
      content: "Colonel Oundroskots",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Ana",
      content: "L'armée au Maroc",
      isRight: true,
      time: "00:42",
      img: null,
      received: false,
    },
    {
      sender: "Ana",
      content: "3aynek njbdha lik anaya!!!!",
      isRight: true,
      time: "00:43",
      img: null,
      received: false,
    },
  ],
  [
    {
      sender: "Lalo Salamnca",
      content: "hi",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Ana",
      content: "hi",
      isRight: true,
      time: "00:42",
      img: null,
      received: false,
    },
    {
      sender: "Lalo Salamnca",
      content: "how's going on your project?",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Lalo Salamnca",
      content: "Do you need any help?",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Ana",
      content: "Hello",
      isRight: true,
      time: "00:42",
      img: null,
      received: false,
    },
    {
      sender: "Lalo Salamnca",
      content: "how's going on your project?",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Lalo Salamnca",
      content: "Do you need any help?",
      isRight: false,
      time: "00:42",
      img: null,
      received: true,
    },
    {
      sender: "Ana",
      content: "Hey there!",
      isRight: true,
      time: "00:42",
      img: null,
      received: false,
    },
    {
      sender: "Ana",
      content: "Hey thereeeeeee!",
      isRight: true,
      time: "00:43",
      img: null,
      received: false,
    },
  ],
  [],
  [],
];
